- name: ArchDevelop1
  hosts: localhost
  tasks:
    - name: "System update cache"
      community.general.pacman:
        update_cache: true
    - name: "System upgrade"
      community.general.pacman:
        upgrade: true
    - name: "Application upgrade"
      ansible.builtin.command: flatpak update --noninteractive
      register: flatpak_update_output
      changed_when: "'app/' in flatpak_update_output.stdout"
    - name: "Ensure stow installed"
      become: yes
      pacman:
        name: stow
        state: present

    - name: "Ensure system components installed"
      become: yes
      pacman:
        name:
          - opendoas
          - bind
          - mtr
          - fd
          - ripgrep
        state: present

    # Security
    - name: "Ensure auditing system is enabled and running"
      become: yes
      ansible.builtin.service:
        name: auditd
        state: started
        enabled: true
    - name: "Ensure AppArmor installed"
      pacman:
        name:
          - apparmor

    - name: "Ensure fastfetch installed"
      become: yes
      pacman:
        name: fastfetch
        state: present
    - name: "Ensure fastfetch dotfiles are configured"
      become: yes
      shell: stow -v -t /home/joergw -S fastfetch
      args:
        chdir: ./dotfiles
        executable: /bin/bash
      register: result
      ignore_errors: true
      changed_when:
        - '"LINK" in result.stderr'
      failed_when: result.rc != 0

    # Desktop
    - name: "Ensure desktop installed"
      become: yes
      pacman:
        name:
          - hyprland
          - hyprlock
          - hypridle
          - uwsm
          - rofi
          - swaync
          - swayidle
          - waybar
          - playerctl
          - brightnessctl
          - flatpak
          - wl-clipboard
          - usbutils
          - bluez
          - bluez-utils
          - pipewire
          - pipewire-pulse
          - pavucontrol
          - cmatrix
          - cava
        state: present
    - name: "Ensure hyprland dotfiles are configured"
      become: yes
      shell: stow -v -t /home/joergw -S hyprland
      args:
        chdir: ./dotfiles
        executable: /bin/bash
      register: result
      ignore_errors: true
      changed_when:
        - '"LINK" in result.stderr'
      failed_when: result.rc != 0
    - name: "Ensure rofi dotfiles are configured"
      become: yes
      shell: stow -v -t /home/joergw -S rofi
      args:
        chdir: ./dotfiles
        executable: /bin/bash
      register: result
      ignore_errors: true
      changed_when:
        - '"LINK" in result.stderr'
      failed_when: result.rc != 0
    - name: "Ensure waybar dotfiles are configured"
      become: yes
      shell: stow -v -t /home/joergw -S waybar
      args:
        chdir: ./dotfiles
        executable: /bin/bash
      register: result
      changed_when:
        - '"LINK" in result.stderr'
      failed_when: result.rc != 0
    - name: "Ensure desktop utilities installed"
      become: yes
      pacman:
        name:
          - fzf
          - unzip
          - bat
        state: present

    - name: "Ensure alacritty installed"
      become: yes
      pacman:
        name:
          - alacritty
          - ttf-meslo-nerd
        state: present
    - name: "Ensure alacritty dotfiles are configured"
      become: yes
      shell: stow -v -t /home/joergw -S alacritty
      args:
        chdir: ./dotfiles
        executable: /bin/bash
      register: result
      ignore_errors: true
      changed_when:
        - '"LINK" in result.stderr'
      failed_when: result.rc != 0

    - name: "Ensure zsh installed"
      become: yes
      pacman:
        name: zsh
        state: present
    - name: "Ensure zsh dotfiles are configured"
      become: yes
      shell: stow -v -t /home/joergw -S zsh
      args:
        chdir: ./dotfiles
        executable: /bin/bash
      register: result
      ignore_errors: true
      changed_when:
        - '"LINK" in result.stderr'
      failed_when: result.rc != 0

    - name: "Ensure tmux installed"
      become: yes
      pacman:
        name: tmux
        state: present
    - name: "Ensure tmux dotfiles are configured"
      become: yes
      shell: stow -v -t /home/joergw -S tmux
      args:
        chdir: ./dotfiles
        executable: /bin/bash
      register: result
      ignore_errors: true
      changed_when:
        - '"LINK" in result.stderr'
      failed_when: result.rc != 0

    - name: "Ensure neovim installed"
      become: yes
      pacman:
        name: neovim
        state: present
    - name: "Ensure neovim dotfiles are configured"
      become: yes
      shell: stow -v -t /home/joergw -S nvim
      args:
        chdir: ./dotfiles
        executable: /bin/bash
      register: result
      ignore_errors: true
      changed_when:
        - '"LINK" in result.stderr'
      failed_when: result.rc != 0
    - name: "Update neovim plugins"
      ansible.builtin.shell: |
        nvim --headless "+Lazy! sync" +qa

    # Developer
    - name: "Ensure nodejs and npm installed"
      become: yes
      pacman:
        name:
          - nodejs
          - npm
          - yarn
          - rust
        state: present
    - name: "Ensure VS Code installed"
      become: yes
      community.general.flatpak:
        name: com.visualstudio.code
        state: present

    # Container Development
    - name: "Ensure container tools installed"
      become: yes
      pacman:
        name:
          - podman
          - podman-compose
          - podman-docker
          - dive
          - nerdctl
        state: present
    - name: "Ensure container desktop tools installed"
      become: yes
      community.general.flatpak:
        name:
          - io.podman_desktop.PodmanDesktop
          - dev.k8slens.OpenLens
        state: present

    # Cloud Development
    - name: "Ensure kubetools installed"
      become: yes
      pacman:
        name:
          - kubectl
          - kubeadm
          - azure-cli
          - azure-kubelogin
          - minikube
          - helm
          - github-cli
        state: present
    - name: "Ensure kube desktop tools installed"
      become: yes
      community.general.flatpak:
        name:
          - dev.k8slens.OpenLens
    - name: "Ensure github installed"
      become: yes
      community.general.flatpak:
        name:
          - io.github.shiftey.Desktop
        state: present

    # Database
    - name: "Ensure database tools installed"
      become: yes
      community.general.flatpak:
        name:
          - org.pgadmin.pgadmin4
        state: present

    # Office
    - name: "Ensure office tools installed"
      become: yes
      community.general.flatpak:
        name:
          - org.mozilla.firefox
          - eu.betterbird.Betterbird
          - org.libreoffice.LibreOffice
        state: present

    # Password Management
    - name: "Ensure Password Manager installed"
      become: yes
      community.general.flatpak:
        name: org.keepassxc.KeePassXC
        state: present

    # Entertainment
    - name: "Ensure Entertainment installed"
      become: yes
      community.general.flatpak:
        name:
          - org.videolan.VLC
          - com.spotify.Client

    # communication: slack
    # 3d printing: freeCAD, [slicer]
    # rest: HTTPie
